#
# http://www.ros.org/wiki/gmapping
#

  
throttle_scans:       1
base_frame:           Pioneer3AT/base_link
map_frame:            Pioneer3AT/map
odom_frame:           Pioneer3AT/odom
map_update_interval:  5.0 

# Unset maxUrange and maxRange and it will autodetect
# maxUrange:          10.0
#sigma:                0.05
sigma:                0.0
kernelSize:           1 
lstep:                0.05
astep:                0.05
iterations:           5 
lsigma:               0.075
ogain:                3.0
lskip:                0

srr:                  0.0
srt:                  0.0
str:                  0.0
stt:                  0.0
#minimumScore:         200


#linearUpdate:         0.5      
#angularUpdate:        0.5 
linearUpdate:         10000      
angularUpdate:        10000 
temporalUpdate:       2.0    

resampleThreshold:    0.5    
particles:            80

# Initial Map Size & Resolution
xmin:                -2
ymin:                -2
xmax:                 2
ymax:                 2
delta:                0.05

llsamplerange:        0.01           
llsamplestep:         0.01
lasamplerange:        0.005  
lasamplestep:         0.005

transform_publish_period:  0.05       
occ_thresh:           0.25
# maxRange:           10.0

tf_delay:             0.1







